[project]
name = "sentencex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["maturin>=1.8.7"]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"
